default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hw_dev

test: &test
  <<: *default
  database: hw_test

production:
  <<: *default
  database: hw_prod
cucumber:
  <<: *test